model_config:
  batch_size: 32
  epochs: 10
  learning_rate: 0.01
  load_before_training: False
  load_model_path: None
  save_model_dir: 'Models/power_forecasting'
  predict_model_path: 'Models/power_forecasting/power_forecasting_epoch_9.pth'
  hidden_dim: 128

tensorboard_save:
  tensorboard_train_dir: 'tensorboard_log/power_forecasting_training'
  tensorboard_eval_dir: 'tensorboard_log/power_forecasting_eval'


data_config:
  data1:
    data_path: 'Data/power_data/merged_power_data1.csv'
    dataset_save_path: 'Data/power_data/dataset1.pkl'
    scaler_save_path: 'Data/power_data/scale1.pkl'
  data2:
    data_path: 'Data/power_data/merged_power_data2.csv'
    dataset_save_path: 'Data/power_data/dataset2.pkl'
    scaler_save_path: 'Data/power_data/scale2.pkl'
  data3:
    data_path: 'Data/power_data/merged_power_data3.csv'
    dataset_save_path: 'Data/power_data/dataset3.pkl'
    scaler_save_path: 'Data/power_data/scale3.pkl'
  data4:
    data_path: 'Data/power_data/merged_power_data4.csv'
    dataset_save_path: 'Data/power_data/dataset4.pkl'
    scaler_save_path: 'Data/power_data/scale4.pkl'

  normalization: 'standard'

  previous_step: 5  
  forecast_step: 12  
  validation_split: 0.2
  

  previous_drop: 
    # - 'wind_speed_10m'
    # - 'wind_direction_10m'
    # - 'wind_speed_30m'
    # - 'wind_direction_30m'
    # - 'wind_speed_50m'
    # - 'wind_direction_50m'
    # - 'wind_speed_70m'
    # - 'wind_direction_70m'
    # - 'temperature_10m'
    # - 'air_pressure'
    # - 'humidity'
    - 'forcast_wind_speed_10m'
    - 'forcast_wind_direction_10m'
    - 'forcast_wind_speed_30m'
    - 'forcast_wind_direction_30m'
    - 'forcast_wind_speed_50m'
    - 'forcast_wind_direction_50m'
    - 'forcast_wind_speed_70m'
    - 'forcast_wind_direction_70m'
    - 'forcast_air_pressure'
    - 'forcast_temperature'
    - 'forcast_humidity'
    # - 'power'

  forecast_drop:  
    - 'wind_speed_10m'
    - 'wind_direction_10m'
    - 'wind_speed_30m'
    - 'wind_direction_30m'
    - 'wind_speed_50m'
    - 'wind_direction_50m'
    - 'wind_speed_70m'
    - 'wind_direction_70m'
    - 'temperature_10m'
    - 'air_pressure'
    - 'humidity'
    # - 'forcast_wind_speed_10m'
    # - 'forcast_wind_direction_10m'
    # - 'forcast_wind_speed_30m'
    # - 'forcast_wind_direction_30m'
    # - 'forcast_wind_speed_50m'
    # - 'forcast_wind_direction_50m'
    # - 'forcast_wind_speed_70m'
    # - 'forcast_wind_direction_70m'
    # - 'forcast_air_pressure'
    # - 'forcast_temperature'
    # - 'forcast_humidity'
    # - 'power'
  target_features:  
    - 'power'


  







    